% bugreportdlg.m creates a window for user input if an undocumented error
% occurs. The user may choose between attaching the complete dataset or not
function [h]=bugreportdlg
set(0, 'DefaultFigureVisible', 'on')
h.f = figure('name','Bugreport',...
    'numbertitle','off',...
    'units','pixels',...
    'position',[500,500,800,200],...
    'toolbar','none',...
    'menu','none');
h.c(1) = uicontrol('style','edit',...
    'units','pixels',...
    'position',[10,75,780,120],...
    'string','Describe what you did when the error occured...',...
    'HorizontalAlignment', 'left',...
    'Max',2);
h.c(2) = uicontrol('style','checkbox','units','pixels',...
    'position',[10,50,200,15],'string','Send debug file');
set(h.c(2),'value',1)
h.p = uicontrol('style','pushbutton','units','pixels',...
    'position',[40,5,90,20],'string','OK',...
    'callback',@p_call);
drawnow     % Necessary to print the message
waitfor(h.f,'Name');
    function [ UI ] = p_call(varargin)
        BR.userreport = get(h.c(1),'String');
        BR.sendFflag = get(h.c(2),'Value');
        set(gcf,'userdata',BR)
        set(gcbf, 'Name', 'Executed')
    end
set(0, 'DefaultFigureVisible', 'off')
end