function pointcorrectCALC
pool.plot=get(gcf,'userdata');
cp=get(gca,'currentpoint');%koordinaten des angeklickten punktes
y=abs(get(pool.plot.Pks,'ydata')-cp(2,2));
x=abs(get(pool.plot.Pks,'xdata')-cp(1,1));
Y=get(pool.plot.Pks,'ydata')';
X=get(pool.plot.Pks,'xdata')';
if ~pool.plot.flagC
    if ~(size(pool.plot.corrFlagint,1)==1)
        if pool.plot.corrFlagint(find(min(x)==x),3)==0
            pool.plot.corrFlagint(find(min(x)==x),3) = 1;
            hold on;
            pool.plot.mPks(find(min(x)==x)) = ...
                plot(...
                X(find(min(x)==x)),...
                Y(find(min(x)==x)),...
                'Marker','x',...
                'MarkerSize',6,...
                'Color','b',...
                'markerfacecolor','b');
        else
            pool.plot.corrFlagint(find(min(x)==x),3) = 0;
            delete(pool.plot.mPks(find(min(x)==x)));
        end
    end
else
    if pool.plot.corrFlagint(find(min(x)==x),3)==0
        pool.plot.corrFlagint(find(min(x)==x),3) = 1;
        hold on;
        pool.plot.mPks(find(min(x)==x)) = ...
            plot(...
            X(find(min(x)==x)),...
            Y(find(min(x)==x)),...
            'Marker','x',...
            'MarkerSize',6,...
            'Color','b',...
            'markerfacecolor','b');
    else
        pool.plot.corrFlagint(find(min(x)==x),3) = 0;
        delete(pool.plot.mPks(find(min(x)==x)));
    end
end
pool.ladder = pool.plot.ladder;
pool.corrFlag = pool.plot.corrFlag;
pool.selF = pool.plot.selF;
if ~pool.plot.flagC
    delete(pool.plot.tags)
    pool.ladder = pool.plot.ladder;
    pool.corrFlag = pool.plot.corrFlag;
    pool.corrFlag{pool.plot.selF,size(pool.corrFlag,2)} = pool.plot.corrFlagint;
    pool.selF = pool.plot.selF;
    [ pool ] = calcTAGpos( pool );
    for label=1:1:size(pool.sTAGpos,1)
        tags(label) = text(pool.sTAGpos(label),pool.sTAGpos(label)-pool.sTAGpos(label)-100,num2str(pool.ladder(label)),'fontsize',5);
        set(tags(label),'Clipping','on');
    end
    pool.plot.tags = tags;
end
if ~(pool.plot.flagC == 1)
    delete(pool.plot.pnote);
    if size(pool.plot.ladder,2)==(size(pool.plot.corrFlagint,1)-sum(pool.plot.corrFlagint(:,3)))
        pool.plot.pnote = annotation('textbox',...
            [0.75 0.8 0.152 0.05],...
            'String',strcat('Peaks found:',{' '},num2str((size(pool.plot.corrFlagint,1)-sum(pool.plot.corrFlagint(:,3))))),...
            'HorizontalAlignment','center',...
            'VerticalAlignment','middle',...
            'FontSize',14,...
            'FontName','Arial',...
            'EdgeColor',[0 0 0],...
            'LineWidth',2,...
            'BackgroundColor',[0.9 0.9 0.9],...
            'FitBoxToText','on',...
            'Tag',strcat(num2str(pool.plot.selF),'.','markerpinfo'),...
            'Color',[0.2 0.6 0.2]);%green
    else
        pool.plot.pnote = annotation('textbox',...
            [0.75 0.8 0.152 0.05],...
            'String',strcat('Peaks found:',{' '},num2str((size(pool.plot.corrFlagint,1)-sum(pool.plot.corrFlagint(:,3))))),...
            'HorizontalAlignment','center',...
            'VerticalAlignment','middle',...
            'FontSize',14,...
            'FontName','Arial',...
            'EdgeColor',[0 0 0],...
            'LineWidth',2,...
            'BackgroundColor',[0.9 0.9 0.9],...
            'FitBoxToText','on',...
            'Tag',strcat(num2str(pool.plot.selF),'.','markerpinfo'),...
            'Color',[0.85 0.20 0]);%red
    end
end
if pool.plot.flagC
    pool.plot.corrFlag{pool.plot.selF,pool.plot.selC} = pool.plot.corrFlagint;
else
    pool.plot.corrFlag{pool.plot.selF,size(pool.plot.corrFlag,2)} = pool.plot.corrFlagint;
end
uistack(pool.plot.Pks,'top');
pool=rmfield(pool,'corrFlag');
pool=rmfield(pool,'selF');
pool=rmfield(pool,'ladder');
set(gcf,'userdata',pool.plot);
end